name: Publish to Blogger

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git log

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Blog Post
        id: generate_post
        run: |
          echo "## Recent Activity" > post.md
          git log --since="1 week ago" --pretty=format:"- %s" >> post.md
          echo "\n## Project Goals" >> post.md
          cat ROADMAP.md >> post.md
          echo "::set-output name=content::$(cat post.md)"

      - name: Publish to Blogger
        uses: some-blogger-action@v1 # Replace with a real Blogger action
        with:
          title: "Weekly Project Update"
          content: ${{ steps.generate_post.outputs.content }}
          blogger_id: ${{ secrets.BLOGGER_ID }}
          api_key: ${{ secrets.BLOGGER_API_KEY }}

